-- Add missing columns for Risk Engine v3.0
ALTER TABLE nba_risk_engine_picks 
ADD COLUMN IF NOT EXISTS archetype TEXT,
ADD COLUMN IF NOT EXISTS h2h_games INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS h2h_avg NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS h2h_hit_rate NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS volatility_pct NUMERIC,
ADD COLUMN IF NOT EXISTS consistency_score NUMERIC,
ADD COLUMN IF NOT EXISTS trend_direction TEXT;